/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.54
 * Generated at: 2015-10-13 10:24:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages.system;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class homepage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>系统管理</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/pages/css/xt_style.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/pages/css/pt_style.css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"/pages/js/public.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/pages/js/jquery-1.7.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/pages/js/jquery.placeholder.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/pages/js/jquery.validate.js\"></script>\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\tvar winhight = document.documentElement.clientHeight;\r\n");
      out.write("\t\tvar mainboxs = winhight-114;\r\n");
      out.write("\t\tdocument.getElementById(\"mainframe\").style.height=mainboxs+\"px\";\r\n");
      out.write("\t\tdocument.getElementById(\"ptlfbg\").style.height=mainboxs+\"px\";\r\n");
      out.write("\t\tdocument.getElementById(\"ptlfbg2\").style.height=mainboxs+\"px\";\r\n");
      out.write("\t});\r\n");
      out.write("\t//窗口最大化最小化事件\r\n");
      out.write("\t$(window).resize(function(){\r\n");
      out.write("\t\tvar winhight = document.documentElement.clientHeight;\r\n");
      out.write("\t\tvar mainboxs = winhight-114;\r\n");
      out.write("\t\tdocument.getElementById(\"mainframe\").style.height=mainboxs+\"px\";\r\n");
      out.write("\t\tdocument.getElementById(\"ptlfbg\").style.height=mainboxs+\"px\";\r\n");
      out.write("\t\tdocument.getElementById(\"ptlfbg2\").style.height=mainboxs+\"px\";\r\n");
      out.write("\t});\r\n");
      out.write("\t$(window).load(function(){\r\n");
      out.write("\t\tif($(\"#state\").val()==\"Y\"){\r\n");
      out.write("\t\t\t userState.showWidow();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\tvar userState={\r\n");
      out.write("\t\t\tshowWidow:function(){\r\n");
      out.write("\t\t\t     var html='<div id=\"msgBox_simScrollCont\" class=\"simScrollCont\" ></div><div  id=\"msgBox\"><div class=\"passwordBox\" id=\"mima\" >'+\r\n");
      out.write("\t\t           '<div class=\"passwordBox2\" ><div class=\"tctitle\">为保证您的账户安全，首次登陆请重置密码！<a href=\"javascript:;\" onClick=\"userState.closeWindow()\" title=\"关闭\"></a></div>'+\r\n");
      out.write("\t\t           '<div id=\"UpdatePwdCenter\"><table width=\"100%\" style=\"margin-left:40px;\" border=\"0\" class=\"mt10\" cellpadding=\"0\" cellspacing=\"0\">'+\r\n");
      out.write("\t\t           ' <tr height=\"50\"> <td align=\"right\" width=\"80\"><label>原密码：</label></td>'+\r\n");
      out.write("\t\t\t       ' <td><input type=\"password\" class=\"grzxnBoxtext\" placeholder=\"请输入当前账号密码\"  id=\"oldpwd\" onBlur=\"userState.oldpwdBlur()\"><span class=\"pzsmsg\">原密码不能为空</span></td>'+\r\n");
      out.write("\t\t\t       ' </tr><tr height=\"50\">  <td align=\"right\" width=\"80\"><label>新密码：</label></td>'+\r\n");
      out.write("\t\t\t       ' <td><input type=\"password\" class=\"grzxnBoxtext\" placeholder=\"请输入6-16位数字或英文密码\" id=\"newpwd\" onBlur=\"userState.newpwdBlur()\"><span class=\"pzsmsg\">6-16位字符密码，只可输入英文或数字！</span></td>'+\r\n");
      out.write("\t\t\t       '</tr> <tr height=\"50\"><td align=\"right\" width=\"80\"><label>重复新密码：</label></td>'+\r\n");
      out.write("\t\t\t       ' <td><input type=\"password\" class=\"grzxnBoxtext\" placeholder=\"请重新输入新密码\" id=\"newpwd2\" onBlur=\"userState.newpwd2Blur()\"><span class=\"pzsmsg\">6-16位字符密码，只可输入英文或数字！</span></td>'+\r\n");
      out.write("\t\t\t       ' </tr><tr height=\"60\"><td></td><td >'+\r\n");
      out.write("\t\t\t       ' <input type=\"button\" class=\"pttcBut85\"  value=\"确认\" onclick=\"userState.updatepwd();\">'+\r\n");
      out.write("\t\t\t       ' <input type=\"button\" class=\"pttcButh85 ml30\" value=\"取消\"  \tonClick=\"userState.closeWindow()\">'+\r\n");
      out.write("\t\t\t       ' </td></tr></table></div><div> </div>';\t \r\n");
      out.write("\t\t\t\t\t$(document.body).append(html);\r\n");
      out.write("\t\t\t\t\tvar left=($(document).width()-$(\"#mima\").width())/2;\r\n");
      out.write("\t\t\t\t\tvar top= ($(document).height()-$(\"#mima\").height())/2;\r\n");
      out.write("\t\t\t\t\t$(\"#mima\").css(\"position\",\"absolute\");\r\n");
      out.write("\t\t\t\t\t$(\"#mima\").css(\"left\",left); \r\n");
      out.write("\t\t\t\t\t$(\"#mima\").css(\"top\",top); \t\r\n");
      out.write("\t\t\t\t\t$(\"#mima\").css(\"display\",\"block\");\t\r\n");
      out.write("\t\t\t\t\t$(\"#msgBox_simScrollCont\").css(\"display\",\"block\");\t\t\t\t\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\tcloseWindow:function(){\r\n");
      out.write("\t\t\t\t$(\"#mima\").remove();\r\n");
      out.write("\t\t\t\t$(\"#msgBox_simScrollCont\").remove();\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tupdatepwd:function(){\r\n");
      out.write("\t\t       if(userState.oldpwdBlur()==true\r\n");
      out.write("\t\t\t\t  &userState.newpwdBlur()==true\r\n");
      out.write("\t\t\t\t  &userState.newpwd2Blur()==true){\r\n");
      out.write("\t\t    \t   var param=\"oldPwd=\"+$(\"#oldpwd\").val()+\"&newPwd=\"+$(\"#newpwd\").val();\t\t\t \r\n");
      out.write("\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\turl:\"updatePwd\",\r\n");
      out.write("\t\t\t\t\t\ttype:\"POST\",\r\n");
      out.write("\t\t\t\t\t\tdata:param,\r\n");
      out.write("\t\t\t\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t\t\t\tif(data!=undefined){\r\n");
      out.write("\t\t\t\t\t\t\t\tif(data.success!=undefined&&data.success==1){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#UpdatePwdCenter\").html('<p class=\"pzscenter\">恭喜你密码修改成功</p>');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t $(\"#mima\").fadeOut(3000,function(){ \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t userState.closeWindow();\t\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t\t\t });  \t\r\n");
      out.write("\t\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#oldpwd\").next().html(\"原密码错误\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#oldpwd\").next().css(\"display\",\"block\"); \r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#newpwd\").next().html(\"原密码错误\");\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#newpwd\").next().css(\"display\",\"block\"); \r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t  }\r\n");
      out.write("\t\t\t} ,\r\n");
      out.write("\t\t\toldpwdBlur:function(){\r\n");
      out.write("\t\t\t\tif($.trim($(\"#oldpwd\").val())==\"\"){\r\n");
      out.write("\t\t\t\t\t$(\"#oldpwd\").next().html(\"原密码不能为空\");\r\n");
      out.write("\t\t\t\t\t$(\"#oldpwd\").next().css(\"display\",\"block\");\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t  }else{\r\n");
      out.write("\t\t\t\t\t$(\"#oldpwd\").next().hide(); \r\n");
      out.write("\t\t\t\t\treturn true\r\n");
      out.write("\t\t\t\t  }\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tnewpwdBlur:function(){\r\n");
      out.write("\t\t\t\tif($.trim($(\"#newpwd\").val())==\"\"){\r\n");
      out.write("\t\t\t\t\t$(\"#newpwd\").next().html(\"6-16位字符密码，只可输入英文或数字！\");\r\n");
      out.write("\t\t\t\t\t$(\"#newpwd\").next().css(\"display\",\"block\");\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t  }if($(\"#newpwd\").val().length>16 || $(\"#newpwd\").val().length<6){\r\n");
      out.write("\t\t\t\t\t  $(\"#newpwd\").next().html(\"请输入6-16位数字或英文密码\");\r\n");
      out.write("\t\t\t\t\t  $(\"#newpwd\").next().css(\"display\",\"block\");\r\n");
      out.write("\t\t\t\t  }else{\r\n");
      out.write("\t\t\t\t\t  $(\"#newpwd\").next().hide(); \r\n");
      out.write("\t\t\t\t\treturn true\r\n");
      out.write("\t\t\t\t  }\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tnewpwd2Blur:function(){\r\n");
      out.write("\t\t\t\tif($.trim($(\"#newpwd2\").val())==\"\"){\t\t\t\r\n");
      out.write("\t\t\t\t\t$(\"#newpwd2\").next().html(\"6-16位字符密码，只可输入英文或数字！\");\r\n");
      out.write("\t\t\t\t\t$(\"#newpwd2\").next().css(\"display\",\"block\");\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t  }if($(\"#newpwd\").val()!=$(\"#newpwd2\").val()){\r\n");
      out.write("\t\t\t\t\t  $(\"#newpwd2\").next().html(\"两次密码不一致\");  \r\n");
      out.write("\t\t\t\t\t  $(\"#newpwd2\").next().css(\"display\",\"block\");  \r\n");
      out.write("\t\t\t\t  }\r\n");
      out.write("\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\t$(\"#newpwd2\").next().hide(); \r\n");
      out.write("\t\t\t\t\treturn true\r\n");
      out.write("\t\t\t\t  }\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"pt-body\" style=\" margin:0px; padding:0px;\"> \r\n");
      out.write("<input type=\"hidden\" id=\"companyId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${topCompanyId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("<input type=\"hidden\" id=\"companyName\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${topCompanyName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("<input type=\"hidden\" id=\"logo\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${topCompanyPic}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("<input type=\"hidden\" id=\"state\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${state}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("<div id=\"ptlfbg\" class=\"ptlfbg\" style=\"margin-top: 114px;\"></div>\r\n");
      out.write("<div id=\"ptlfbg2\" class=\"ptlfbg2\" style=\"margin-top: 114px;\"></div>\r\n");
      out.write("<iframe height=\"114px\" id=\"topframe\" name=\"topframe\" width=\"100%\"  scrolling=\"no\" frameborder=\"0\" allowtransparency=\"true\" src=\"/pages/top.jsp\"></iframe>\r\n");
      out.write("<iframe id=\"mainframe\" height=\"100%\" width=\"100%\"  scrolling=\"no\" frameborder=\"0\" allowtransparency=\"true\" src=\"/ipavMain\" style=\"bz-index: 1;margin-left: 8px;\"></iframe>\r\n");
      out.write("<div id=\"_ptlfbg\" style=\"display:none;position: absolute;width: 8px;background: none repeat scroll 0% 0% #000;top: 0px;left: 0px;opacity: 0.4;margin-top: 114px;\"></div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
