/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.54
 * Generated at: 2015-10-13 10:24:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class top_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>系统管理</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/pages/css/xt_style.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/pages/css/pt_style.css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"/pages/js/jquery-1.7.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/pages/js/jquery.placeholder.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/pages/js/jquery.validate.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(function(){\r\n");
      out.write("\t\t\t$('input').placeholder();\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function getCurDate()\r\n");
      out.write("{\r\n");
      out.write(" var d = new Date();\r\n");
      out.write(" var week;\r\n");
      out.write(" switch (d.getDay()){\r\n");
      out.write(" case 1: week=\"星期一\"; break;\r\n");
      out.write(" case 2: week=\"星期二\"; break;\r\n");
      out.write(" case 3: week=\"星期三\"; break;\r\n");
      out.write(" case 4: week=\"星期四\"; break;\r\n");
      out.write(" case 5: week=\"星期五\"; break;\r\n");
      out.write(" case 6: week=\"星期六\"; break;\r\n");
      out.write(" default: week=\"星期天\";\r\n");
      out.write(" }\r\n");
      out.write(" var years = d.getYear()-100;\r\n");
      out.write(" var month = add_zero(d.getMonth()+1);\r\n");
      out.write(" var days = add_zero(d.getDate());\r\n");
      out.write(" var hours = add_zero(d.getHours());\r\n");
      out.write(" var minutes = add_zero(d.getMinutes());\r\n");
      out.write(" var seconds=add_zero(d.getSeconds());\r\n");
      out.write(" var ndate = years+\"年\"+month+\"月\"+days+\"日  \" +hours+ \":\"+minutes+\":\"+seconds+\"&nbsp;&nbsp;&nbsp;&nbsp;\"+week;\r\n");
      out.write(" divT.innerHTML= ndate;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function add_zero(temp)\r\n");
      out.write("{\r\n");
      out.write(" if(temp<10) return \"0\"+temp;\r\n");
      out.write(" else return temp;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("setInterval(\"getCurDate()\",100);\r\n");
      out.write("\r\n");
      out.write("//按enter键触发搜索框\r\n");
      out.write("function CheckEnterKey(evt) \r\n");
      out.write("{ \r\n");
      out.write("if(evt.keyCode == 13) \r\n");
      out.write("{\t \r\n");
      out.write(" window.location.href=document.getElementById(\"sercha\").href;\r\n");
      out.write(" alert(\"d\");\r\n");
      out.write("} \r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t$(\"#logo\").attr(\"src\",$('#logo', window.parent.document).val());\r\n");
      out.write("\t$(\"#companyName\").html($('#companyName', window.parent.document).val());\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("function quit(){\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl:\"/quit\",\r\n");
      out.write("\t\ttype:\"POST\",\r\n");
      out.write("\t\tsuccess:function(data){\r\n");
      out.write("\t\t\tconsole.log(data)\r\n");
      out.write("\t\t\tif(data.result!=undefined)\r\n");
      out.write("\t\t\t\twindow.parent.location.href=data.result;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t})\r\n");
      out.write("}\r\n");
      out.write("function refreshLogo(){\r\n");
      out.write("\tvar companyid=$('#companyId', window.parent.document).val();\r\n");
      out.write("\t$.post(\"/getCompanyLOGO\",{\"companyid\":companyid},function(data){\r\n");
      out.write("\t\tif(data!=null)\r\n");
      out.write("\t\t\t$(\"#logo\").attr(\"src\",data.logo);\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"pt-body\"> \r\n");
      out.write("\r\n");
      out.write("<div class=\"pt-top\">\r\n");
      out.write("\t<div class=\"pt-topcen\">\r\n");
      out.write("    \t<div class=\"pt-qylogo\" onclick=\"refreshLogo()\">\r\n");
      out.write("        \t<img id=\"logo\" src=\"/pages/images/platform/qylogo.png\">\r\n");
      out.write("            <p id=\"companyName\">天道启科</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"pt-top-rt\">\r\n");
      out.write("    \t\t<div class=\"pt-rt-logo\"></div>\r\n");
      out.write("            <a href=\"#1\" class=\"pt-close\" onclick=\"quit()\">安全退出</a>\r\n");
      out.write("            <p id=\"divT\" class=\"pt-time mr20\"></p>\r\n");
      out.write("    \t</div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"pt-tfg\"></div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"pt-tmenu\">\r\n");
      out.write("\t<div class=\"toolmenu\">\r\n");
      out.write("    \t<ol>\r\n");
      out.write("        \t<li><div id=\"mainframe\" class=\"ptworks\">工作平台</div></li>\r\n");
      out.write("            <!-- <li><div>我的工资</div><a href=\"#1\" class=\"pt-muclose\" title=\"关闭\"></a></li> -->\r\n");
      out.write("        </ol>\r\n");
      out.write("    </div>\r\n");
      out.write("\t<div class=\"pt-serach\">\r\n");
      out.write("\t\t<input type=\"text\" class=\"pt-serachwb\" placeholder=\"请输入查询内容\">\r\n");
      out.write("       \t<a href=\"#1\" class=\"sercha\"></a>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"simScrollCont12\" class=\"simScrollCont\"></div>\r\n");
      out.write("<!-- 说说图片遮罩层 -->\r\n");
      out.write("<div id='fatherMask' class='uphotobg'></div>\r\n");
      out.write("<!-- 普通遮罩层-->\r\n");
      out.write("<div id='fatherScrollCont' class='simScrollCont' ></div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
